# Generated by Django 6.0.3 on 2026-03-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=255, verbose_name='ФИО студента')),
                ('group_name', models.CharField(db_index=True, max_length=100, verbose_name='Название группы')),
                ('task_type', models.CharField(choices=[('html', 'HTML/CSS'), ('js', 'JavaScript'), ('python', 'Python'), ('english', 'English')], db_index=True, default='python', max_length=20, verbose_name='Тип задания')),
                ('task_description', models.TextField(verbose_name='Условие задания')),
                ('student_code', models.TextField(verbose_name='Код или текст ответа студента')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Оценка (0–100)')),
                ('ai_feedback', models.TextField(blank=True, null=True, verbose_name='Полный комментарий ИИ')),
                ('short_comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое резюме')),
                ('is_ai_generated', models.BooleanField(default=False, verbose_name='Сгенерировано ИИ?')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('processing', 'Проверяется'), ('completed', 'Проверено'), ('error', 'Ошибка')], db_index=True, default='pending', max_length=20, verbose_name='Статус проверки')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время сдачи')),
            ],
            options={
                'verbose_name': 'Сдача задания',
                'verbose_name_plural': 'Сдачи заданий',
                'ordering': ['-created_at'],
            },
        ),
    ]
